const shopActionTypes = {
  FETCH_COLLECTIONS_START: "shop/FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "shop/FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "shop/FETCH_COLLECTIONS_FAILURE",
  SET_FILTER: "shop/SET_FILTER",
};

export default shopActionTypes;
